# Custom favicon name
favicon: favicon.png

# Page languagge
lang: zh-cn

# Keyword for SEO
keywords: "Typing"

# Separate Post title and Blog title
separator: '-'

# Index Nav menu
menu:
  Archives: /archives
  About: /about

# Index GitHub Link
github:
  name:
  link:

# Comment settings
comment:
  enable: false
  type: disqus
  disqus:
    shortname:
    mirror: false
    api: 
    apiKey: 
    admin: 
    adminLabel: 

# Footer infomation
footer:
  copyright:
  beian:
  ga: